### ISSUE TITLE
Save State

### ISSUE THREAD

**Issue by summerock** [simon-paris/gba.ninja#1]
Nicely done. 

How do i save my progress manually to get the .sgm file? Has it been implemented?

**Comment by simon-paris** [comment]
Nope, it's not implemented. The save state binding is commented out here: https://github.com/simon-paris/gba.ninja/blob/master/src/gba/GBA.cpp#L4636

If you uncomment it and created a js binding for it in `emscripten/VBA.cpp` like this it might work but I haven't tried:

```
int maxSizeOfSaveState = 0x10000000;
ENTRY_FN VBA_write_state (int cycles) {
    void *mem = malloc(maxSizeOfSaveState);
    unsigned int size = emulator.emuWriteState(mem, 0);
    return (int) mem;
}
```
