### ISSUE TITLE
help to run

### ISSUE THREAD

**Issue by cloudffx** [simon-paris/gba.ninja#12]
I used following commands on win10:
npm install yargs
node build --opt
webpack

then open build/index.html，get errors on console:

TypeError: f(...) is not a function index.html:1:1488030
file:///D:/Work/gba.ninja/build/index.html:1:1488030
file:///D:/Work/gba.ninja/build/index.html:1:105
file:///D:/Work/gba.ninja/build/index.html:1:902
file:///D:/Work/gba.ninja/build/index.html:1:2
ajaxScript/xhr.onload
file:///D:/Work/gba.ninja/build/index.html:699:21

thanks!

**Comment by simon-paris** [comment]
It doesn't work if you open it like that, you need a server to host it. Try setting up xampp.

**Comment by cloudffx** [comment]
Thanks for the replay!
When I run it on xampp, there are still errors. Am I missing something?

sw fetch [ignore] https://www.googletagmanager.com/gtag/js?id=UA-45495852-6
sw.js:1 sw fetch [network] http://localhost:83/gba/emu.js
sw.js:1 sw fetch [network] http://localhost:83/gba/emu.wasm
sw.js:1 sw fetch [ignore] chrome-extension://jgphnjokjhjlcnnajmfjlacjnjkhleah/js/btype.js
(index):103 Remote logged:  Uncaught TypeError: gbaninja.ccall is not a function;  Source: http://localhost:83/gba/;  Line: 543;  Col: 33;  Message: gbaninja.ccall is not a function;  StackTop: at Object.VBAInterface.VBA_get_emulating (http://localhost:83/gba/:543:33); 
(index):543 Uncaught TypeError: gbaninja.ccall is not a function
    at Object.VBAInterface.VBA_get_emulating ((index):543)
    at o.handleAudioEvent (app.js:2)
VBAInterface.VBA_get_emulating @ (index):543
o.handleAudioEvent @ app.js:2
(index):103 Remote logged:  Uncaught TypeError: gbaninja.ccall is not a function;  Source: http://localhost:83/gba/;  Line: 543;  Col: 33;  Message: gbaninja.ccall is not a function;  StackTop: at Object.VBAInterface.VBA_get_emulating (http://localhost:83/gba/:543:33); 
(index):543 Uncaught TypeError: gbaninja.ccall is not a function
    at Object.VBAInterface.VBA_get_emulating ((index):543)
    at o.handleAudioEvent (app.js:2)

**Comment by simon-paris** [comment]
I'm not sure what that is.

(Sorry I forgot about this issue)
