### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by Slluxx** [simon-paris/gba.ninja#13]
I am unable to install anything.
So first of all you cant use python 3. you must use python 2.7 (which you can install via ` npm install --global --production windows-build-tools` an an *administrator powershell* window.)

The next problem is node-gyp (required while installing `npm i emcc --save`), which does not seem to work with node 10 as it will simply fail to download files, like ` ERR! Tried to download(404): https://axonodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.22.2-node-v64-win32-x64.tar.gz`

sadly thats enough for me to not continue trying this out. i had big plans but if it already requires that much and cannot even install properly - its not a great thing. Seemed promising - but ill pass.

**Comment by simon-paris** [comment]
You should try following these instructions for installing emscripten: http://kripken.github.io/emscripten-site/docs/getting_started/downloads.html

It comes bundled with appropriate versions of python and node. The emsdk_env scripts add node, python, and emcc to your path.

**Comment by Slluxx** [comment]
i tried that aswell and it installs the right python version etc but i think it doesnt add emcc but rather emsdk to the path. Well, yesterday i was angry and tired so i have to check again today

**Comment by Slluxx** [comment]
```
Adding directories to PATH:
PATH += H:\emsdk

Setting environment variables:
EMSDK = H:/emsdk
EM_CONFIG = C:\Users\Sllux\.emscripten

H:\emsdk>
```

its emsdk and not emcc

**Comment by Slluxx** [comment]
i did. its still not working but i cant remember the error message (at work right now)

**Comment by GregoryTheGamer** [comment]
Sorry to hop in here Slluxx but I need to ask simon if he can update the copyright info to 2018.

**Comment by Slluxx** [comment]
@GregoryTheGamer this is inappropriate.

You could have open your own issue for you own, very different problems and needs or even better you could do it on your own and make a pull request to fix whatever you need and take work off the devs.

Anyway, i am not using/trying to use this solution anymore. this issue can be closed.

**Comment by simon-paris** [comment]
@GregoryTheGamer done
