### ISSUE TITLE
Gamepad support

### ISSUE THREAD

**Issue by Jammster** [simon-paris/gba.ninja#17]
This is more of an suggestion than an issue, but would it be possible to add gamepad support to this emulator? It would be amazing if you could make it work!

**Comment by simon-paris** [comment]
I'd like to do that but I don't have the time. It's on my todo list. Thanks for the suggestion.

**Comment by danimesq** [comment]
@simon-paris
If it is really on your todo list, you could reopen this issue and add labels.
