### ISSUE TITLE
Cheat Support?

### ISSUE THREAD

**Issue by GregoryTheGamer** [simon-paris/gba.ninja#2]
Hey, do you plan on adding support for gameshark, action replay, codebreaker, ect., codes. I would like to know as a curious question. Thanks! Gregory

**Comment by simon-paris** [comment]
I was planning on eventually adding save states and frameskip fast-forward. I wasn't planning on adding cheat support but I will if there's enough demand.

Thanks!

**Comment by GregoryTheGamer** [comment]
kk, I understand you have other things to do first, I will still wait for cheat support. Thanks!
(P.S. What about multiplayer linking I.E. Pokemon and other related games? Whats your plan on that?)

**Comment by simon-paris** [comment]
👌.

I won't do linking because it wouldn't be possible to get it to perform well.

**Comment by GregoryTheGamer** [comment]
Btw is there a easier way to contact you (I'd be happy to keep in touch with ya)
