### ISSUE TITLE
Electron: save savegame on ROM`s folder

### ISSUE THREAD

**Issue by DaniellMesquita** [simon-paris/gba.ninja#20]

**Comment by Zelif** [comment]
What issue are you having with Electron and the saves? 

If you want to save to a folder then use 
```
VBASaves.exportSave(romcode)
```JavaScript
Check out this file for other JS interfaces for saves:
[Saves.js](https://github.com/simon-paris/gba.ninja/blob/master/Saves.js)

**Comment by DaniellMesquita** [comment]
It already haves an Electron release?

**Comment by Zelif** [comment]
> It already haves an Electron release?

There is no special build for it, but I just hosted it in electron and it seemed to work fine. Is there an issue that you are hitting with electron? ( I only tested it for a few seconds but looked fine )

**Comment by DaniellMesquita** [comment]
It could write a save file on ROM`s folder, readable by other emulators

**Comment by DaniellMesquita** [comment]
Well, it is a emscripten port? Then all its features are ported to Electron APIs?

**Comment by Zelif** [comment]
> It could write a save file on ROM`s folder, readable by other emulators
This would be an upstream issue not for this repository. This project is based off VBA-m and you would need the authors of that project to support other save file types from different emulators. 

[VBA-m link](https://github.com/visualboyadvance-m/visualboyadvance-m)

>Well, it is a emscripten port? Then all its features are ported to Electron APIs?
You will need to overwrite the VBASaves.exportSave  function to use the Electron native dialogs. 

[Dialog API](https://electronjs.org/docs/api/dialog)

`Javascript
VBASaves.prototype.exportSave = function (romCode) {
    let save = this.getSave(romCode);
    const targetPath = "C:\\SOME PATH TO ROMS\"
    if (!save) {
        throw new Error("No save found for " + romCode);
    }

    let reader = new FileReader();
    const {remote} = require('electron'),
    fs = require('fs'),
    dialog = remote.dialog,
    currentWindow = remote.getCurrentWindow();

    let options = {
        title: "Save file - Electron example",
        defaultPath : `${defaultPath}\${romCode} ${require("./romCodeToEnglish")(romCode)}`,
        buttonLabel : "Export Rom Save",
        filters :[
            {name: 'Rom Saves', extensions: ['sav']}
        ]
    }
    dialog.showSaveDialog(currentWindow , options, (filename) => {
        if(filename){
	    reader.onload = _ => {
	        if (reader.readyState == 2) {
	             var buffer = new Buffer(reader.result);
	             fs.writeFile(filename, buffer, (error) => {
	                  // Do some error handling
	             });
	        }
	    };
            let blob = new Blob([save], {contentType: "application/octet-stream"});
            reader.readAsArrayBuffer(blob);
        }
    });
}
`
This should work*** Haven't tested a single thing with it. But should put you on the right path. 
The way I did it the other day was a hacky kinda way of just invoking a url (blob in this case) to save, but this way will result in a better experience. 

That said this is doing it in the render loop and should be done on the main loop by passing the buffer via IPC to main and then saving the file on the main loop. This way it doesn't interfere with the UI. 

You can forgo the dialog all together and have them set to a location. 

Importing would have to be changed also. You could always fork the project yourself and give it a try to put in Electron. I don't think there is much else other than saving that would need to be changed. Have you run into any other issues running it in Electron?
