### ISSUE TITLE
Cheats and speed

### ISSUE THREAD

**Issue by aikenJa** [simon-paris/gba.ninja#21]
There is no way to use cheats in online emulator.

In addition, there is no speed up feature that I love because it helps skip annoying things.

**Comment by simon-paris** [comment]
Yeah I'd like to implement speedup when I get the time. It's on my todo list.

No plans to implement cheats right now.

**Comment by LocatedBiome** [comment]
> Yeah I'd like to implement speedup when I get the time. It's on my todo list.
> 
> No plans to implement cheats right now.

Is there a speed-up feature yet?
