### ISSUE TITLE
Audio not working

### ISSUE THREAD

**Issue by papapasta** [simon-paris/gba.ninja#22]
The audio doesn’t appear for safari browser

**Comment by Zelif** [comment]
Version of Safari ? 

Safari does use a prefixed version but I can see that has been accounted for. 

But if your version of safari is less than 6.1 (MacOS 10.7 2014) audio will not work. 

If you have version 11+ (2017?) you will need to get the fix I made for the chrome audio not working. 
[Outlined Here](https://github.com/simon-paris/gba.ninja/pull/19)

Basically audio is not able to be auto played, it requires user interaction then the audio can work. 

I didn't know that Safari implemented this auto play limit as well as Chrome.

**Comment by simon-paris** [comment]
It should be fixed now, I don't have safari to test though. Let me know if it doesn't work, thanks!
