### ISSUE TITLE
Real Time Clock Setting

### ISSUE THREAD

**Issue by summerock** [simon-paris/gba.ninja#23]
Is there a way to config the Real Time Clock Setting to make it work?

All games currently have real-time clock set at 12 and it doesn't change at all.

Here is a post about it.

https://github.com/visualboyadvance-m/visualboyadvance-m/issues/211#issuecomment-403499893

**Comment by Xcallono** [comment]
Look at this.
https://github.com/visualboyadvance-m/visualboyadvance-m/issues/579
The main RTC option is a bit confusing. Furthermore, Fire Red doesn't by default HAVE this item. You have to patch SIIRTC_V into the ROM.

**Comment by LocatedBiome** [comment]
can this be closed? its been open and answered for almost 2 years
