### ISSUE TITLE
wont load

### ISSUE THREAD

**Issue by tjkerr2213** [simon-paris/gba.ninja#3]
not sure if you will read this but none of my roms load since the new update please help thanks

**Comment by simon-paris** [comment]
Hi, what ROM are you trying to load and what browser are you using?

**Comment by tjkerr2213** [comment]
i actually got it to load after awhile i just had to do a system reboot

**Comment by tjkerr2213** [comment]
do you think gameboy suppport will make it here?

**Comment by simon-paris** [comment]
I might do gameboy support eventually, but I have lots of other cool features to add first.

**Comment by tjkerr2213** [comment]
like what or is that a mystery

**Comment by simon-paris** [comment]
* Performance improvements
 * Google drive sync for save files
 * Support for loading zip files
 * Support for loading ROM from url
 * Save state support

**Comment by tjkerr2213** [comment]
thank you very much for this emulator
