### ISSUE TITLE
no cheat code support and cant find the 4 digit code for importing saves

### ISSUE THREAD

**Issue by shrekster9000** [simon-paris/gba.ninja#30]
Hi! i was using gba.ninja and i realized everything got wiped including my data so imported it but i couldnt find the 4 digit code (mario kart super circuit) and when i first started using it i saw there was no way to implement them if anyone could find me the code that would be much appreciated

**Comment by simon-paris** [comment]
The code for mario kart super circuit is `AMKE` (USA) or `AMKP` (Europe). When you exported it, the code would have been in the filename.

There's no cheat code support, sorry.
