### ISSUE TITLE
Proformance stats There are problems

### ISSUE THREAD

**Issue by goldenking277** [simon-paris/gba.ninja#4]
The proformances states arnt working the proformance isnt showing up and if there something sapposed to show up can it be to change the speed of how it runs and can u add cheats.

**Comment by simon-paris** [comment]
The stats should show up while you're holding the Backquote key (to the left of the 1 key).

Changing the speed and cheat support is coming eventually.

**Comment by GregoryTheGamer** [comment]
its ` that key (I call it the grave key personally (as its the same key used to open the valve developer console)

**Comment by I-am-me-not-you** [comment]
is there a way to change the button format, I'm used to the a&b being switched

**Comment by simon-paris** [comment]
Yeah, the Keyboard Binding menu. You click the rebind button then press the key you want to use.

**Comment by I-am-me-not-you** [comment]
i tried that but it doesn't work
