### ISSUE TITLE
Module isn't loading

### ISSUE THREAD

**Issue by adamslr** [simon-paris/gba.ninja#5]
![screenshot 2017-10-27 at 1 54 45 pm](https://user-images.githubusercontent.com/30200964/32118102-89b03d3e-bb1e-11e7-95c9-a934f6a1d26e.png)

I used to be able to run it now it won't load, also works for friend with same computer.

**Comment by simon-paris** [comment]
😢

Alright, it should be fixed now. Thanks for letting me know.
