### ISSUE TITLE
Better handling of homemade roms (invalid romCode)

### ISSUE THREAD

**Issue by ahirschberg** [simon-paris/gba.ninja#7]
I love this project, and have been looking at integrating your emulator into my site to demo a GBA game I wrote. I noticed that the recently added ROM code check in the project blocks many homebrew games from loading. These games don't have a valid rom code at offset 0xAC (it's all 0s) and thus the more recent gba.ninja codebase refuses to load them. However, going into the javascript debugger and force bypassing that check results in my game loading and fully playable. Mednafen. VisualBoyAdvance, and older versions of your emulator have no issues playing this game as compiled.

Here is my rom at offset 0xA0-0xAF (all null bytes)
```
0000a0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  >................<
```

Links:
[failing ROM (zipped)](https://github.com/simon-paris/gba.ninja/files/1500328/HelmetMan.zip)
[ROM makefile](https://github.com/ahirschberg/helmet_man_gba/blob/515a96b2ca6da9a6d051915aa510e6f3a83b841b/Makefile)

Thanks! :video_game:

**Comment by simon-paris** [comment]
Got it, I'll fix it tonight.

**Comment by simon-paris** [comment]
It's done
